# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestQ1day15():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_q1day15(self):

        expectedurl = "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
        self.driver.get(expectedurl)

        actualurl=self.driver.current_url
        assert self.driver.title == "OrangeHRM"
        assert expectedurl==actualurl