# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab2(self):
    self.driver.get("https://demo.opencart.com/")
    self.driver.set_window_size(788, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".show > .fa-caret-down").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    time.sleep(3000)
    self.driver.find_element(By.ID, "input-email").click()
    self.driver.find_element(By.ID, "input-email").send_keys("sow@gmail.com")
    self.driver.find_element(By.ID, "input-password").click()
    self.driver.find_element(By.ID, "input-password").send_keys("sow345")
    self.driver.find_element(By.CSS_SELECTOR, ".text-end:nth-child(5) > .btn").click()
  
